version: '3'
services:
    restreamer:
        image: datarhei/restreamer
        ports:
            - "8080:8080"
        networks:
            - frontend
        volumes:
            - "~/db:/restreamer/db"
        environment:
          - RS_USERNAME=dispatch
          - RS_PASSWORD=admin
          - RS_LOGLEVEL=4
          - RS_TIMEZONE=America/Los_Angeles
          - RS_SNAPSHOT_INTERVAL=1m
        deploy:
          replicas: 1
          restart_policy:
            condition: any
            delay: 5s
            window: 10s
networks:
  frontend:
